---
title: "EV Power - Lab 4 Project Report"
format: typst
---

# Example Solution 1

## **Part 0: libraries**

```{r}
library(tidyverse)
library(readr)

renew_2021 <- read.csv("data/renew-use-2021.csv")
renew_2022 <- read.csv("data/renew-use-2022.csv")
renew_2023 <- read.csv("data/renew-use-2023.csv")

total_2021 <- read.csv("data/total-use-2021.csv")
total_2022 <- read.csv("data/total-use-2022.csv")
total_2023 <- read.csv("data/total-use-2023.csv")

av_energy_2021_2023 <- read.csv("data/av-energy-price-2021-2023.csv")
ev_registration_2021_2023 <- read.csv("data/ev-registrations-by-state-2023.csv")
```

## **Part 1:** **Defining Research Question**

Chosen Question:  What is the share of electricity that comes from clean sources by state?

## **Part 2: Data Preparation and Cleaning**

```{r}
renew_2023$State <- toupper(renew_2023$State)
renew_2023 <- renew_2023 |>
    mutate(Renewable_Use_2023 = str_extract(
    Renewable_Use_2023,
    "\\d+\\.?\\d*"
  )) |>
    mutate(Renewable_Use_2023 = as.numeric(Renewable_Use_2023))


renewable_summary <- renew_2023 |>
  group_by(State, Energy_Source) |>
  summarise(Total_Use = sum(Renewable_Use_2023, na.rm = TRUE), .groups = 'drop') |>
  pivot_wider(
    names_from = State,
    values_from = Total_Use,
  ) |>
  rename(Energy_Source = Energy_Source)
```

## **Part 3: Joining / Pivoting Datasets for Analysis**

```{r}

```

## **Part 4: Mapping Visualization**

```{r}

```
